config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  patch "events/:id/add_pictures" => "events#add_pictures", as: "add_pictures"

  resources :events do
    resources :participations, only: [:create]
    resources :messages, only: [:create]
  end
  get '/profile' => 'users#profile'
  post '/users/random' => 'users#random'
  resources :users, only: [ :edit, :update, :destroy ]
  resources :participations, only: [:update, :destroy]
  resources :activities, only: [:index]
  mount Attachinary::Engine => "/attachinary"
  get 'activities/:id/done' => "activities#mark_as_read", as: :read_activity
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-4 col-md-offset-4">
        <div class="social-network">
          <ul class="list-inline text-center">
            <li>
              <div class="social-icons">
                <a id="icon-insta" class="text-center" href="#">
                  <i class="fa fa-instagram">
                  </i>
                </a>
              </div>
            </li>

            <li>
              <div class="social-icons">
                <a id= "icon-fb" class="text-center" href="#">
                  <i class="fa fa-facebook-official">
                  </i>
                </a>
              </div>
            </li>

            <li>
              <div class="social-icons">
                <a id= "icon-twitter" class="text-center" href="#">
                  <i class="fa fa-twitter-square">
                  </i>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <% if user_signed_in? %>
      <%= link_to t(".top_call_to_action", default: "Prochains Run"), events_path, class: "button button_green" %>
    <% else %>
      <%= link_to 'Connexion', new_user_session_path, class:"button button_green" %>
    <%end %>

  </div>

  <div class="navbar-center">
   <%= link_to root_path, class: "navbar-wagon-brand" do %>
     <%= image_tag "logo-main.svg" %>
   <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <button type="button" class="button button_green" data-toggle="modal" data-target="#new_event_form">
        Nouveau Run
      </button>

      <!-- Notification -->
      <div class="navbar-wagon-item" id="notifications">
        <%= render 'shared/notifications', activities: @activities %>
      </div>
    </div>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="dropdown-toggle" , id="navbar-wagon-menu", data-toggle="dropdown", aria-hidden="true">
            <span class= "white-name">
              <i class="fa fa-user no-btn" id="character"></i>
              <%= current_user.first_name %> <%= current_user.last_name %>
            </span>
        </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
               <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Inscription"), new_user_registration_path, class: "button button_green", id: "login-btn" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <div id="new_event_form" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center title-modal" id="gridModalLabel">Créer un nouvel événement</h4>
        </div>
        <div class="modal-body">
          <div class="container-fluid bd-example-row">
            <%= render 'events/new', event: Event.new %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_notifications.html.erb
<div class="dropdown" style="margin-left: 25px;">
  <div class="dropdown-toggle" , id="navbar-wagon-menu", data-toggle="dropdown", aria-hidden="true">
    <span class= "white-name">
      <div class="badge-container">
        <i class="fa fa-bell-o no-btn" style="color: white;"></i>
        <% nbr_activities = activities.count %>
        <% unless nbr_activities == 0 %>
          <div class="badge badge-blue-light no-btn">
            <%= nbr_activities %>
          </div>
        <% end %>
      </div>
    </span>
</div>
<ul class="dropdown-menu dropdown-menu-right" style="width: 600px;padding: 20px 25px;">
  <h4 style="color: #333333;">Notifications <i class="fa fa-times" style="font-size:14px;    position: absolute;right: 10px;top: 6px;color: grey;"></i></h4>
  <%= render "activities/index", activities: activities %>
</ul>