config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  patch "events/:id/add_pictures" => "events#add_pictures", as: "add_pictures"

  resources :events do
    resources :participations, only: [:create]
    resources :messages, only: [:create]
  end
  get '/profile' => 'users#profile'
  post '/users/random' => 'users#random'
  resources :users, only: [ :edit, :update, :destroy ]
  resources :participations, only: [:update, :destroy]
  resources :activities, only: [:index]
  mount Attachinary::Engine => "/attachinary"
  get 'activities/:id/done' => "activities#mark_as_read", as: :read_activity
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  has_attachments :photos, maximum: 10

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  MEETING = ["Run rapide", "Run fractionné", "Run endurance", "Blabla run", "Marche rapide", "Marche plaisante"]

  validates :type_of, inclusion: { in: MEETING }
  validates :datetime, presence: true
  validates :private, :inclusion => { :in => [true, false] }
  validates :meeting_point, presence: true
  validate :goal

  def goal
    if time_goal.nil? && trail_goal.nil?
      errors.add(:time_goal, "You have to choose a goal")
      errors.add(:trail_goal, "You have to choose a goal")
    end
  end

  def time_goal_to_s
    return "" if time_goal.nil?
    hours = time_goal / 60
    min = time_goal % 60
    min = "0#{min}" if min < 10
    hours == 0 ? "#{min} min" : "#{hours}h#{min} min"
  end

  def start_time
      self.datetime.strftime('%e %B %Y') ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end

  def joined?(user)
    self.participations.map(&:user).include?(user)
  end

  def self.my_private_events(user)
    events = Event.where(private: true)
    events.map do |event|
      event.joined?(user)
    end
    events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :show, :edit, :update, :destroy, :add_pictures ]

  def index
    @public_events = policy_scope(Event).where(private: false)
    @my_private_events = policy_scope(Event).my_private_events(current_user)
    @filter = params[:filter]

    if @filter == 'public'
      @events = Event.joins(:user).where(private: false, users: {company: current_user.company})
    elsif @filter == 'Own_run'
      @events = Event.where(user_id: current_user)
      @my_participations = current_user.events_only_as_participant
    elsif @filter == 'private'
      @events = current_user.private_events
      p @events
    elsif @filter == 'refused'
      @events = currener.refused_events
    elsif @filter == 'challenge'
      @events = Event.joins(:user).where.not(users: {company: current_user.company})
    else
      @events = Event.where(private: false) + current_user.private_events
      @events.sort_by! { |ev| ev[:datetime].to_i }
    end
    @events_sorted = @events.group_by{ |e| e.datetime.to_date }
    @my_participations_sorted = @my_participations.group_by{ |e| e.datetime.to_date } if @my_participations
  end

  def show
    @message = Message.new(event_id: @event.id)
    @events = Event.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      if event.latitude && event.longitude
        marker.lat event.latitude
        marker.lng event.longitude
      end
    end
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    invited_users_id = params['event']['user_ids']
    invited_users_id.shift
    if params['event']['user_id'].present?
      invited_users_id << params['event']['user_id']
    end
    params = event_params

    if params['datetime'].present?
      time = Time.new(2000, 01, 01, event_time_params['hour'], event_time_params['minute'], 0, "+02:00")
      params['datetime'] = event_params['datetime'].to_datetime + time.seconds_since_midnight.seconds
    end

    @event = Event.new(params)
    @event.user = current_user
    @participation = Participation.new(status: "going")
    @participation.user = current_user
    @participation.event = @event
    authorize @event

    if @event.save && @participation.save
      if invited_users_id.present?
        invited_users_id.each do |user_id|
          Participation.create(event_id: @event.id, user_id: user_id, status: "maybe")
        end
      end
      @event.create_activity :create, owner: current_user
      respond_to do |format|
        format.html { redirect_to event_path(@event) }
        format.js  # <-- 'app/views/events/create.js.erb'
      end
    else
      respond_to do |format|
        format.html { render 'new', event: @event }
        format.js  # <-- 'app/views/events/create.js.erb'
      end
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      @event.create_activity :update, owner: current_user
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.create_activity :destroy, owner: current_user
    @event.destroy
    redirect_to events_path
  end

  def add_pictures
    @event.update(event_picture)
    redirect_to event_path(@event)
  end

  private

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:datetime, :private, :type_of, :description,
      :meeting_point, :address, :time_goal, :trail_goal)
  end

  def event_time_params
    params.require(:date).permit(:hour, :minute)
  end

  def event_picture
    params.require(:event).permit(photos: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_css_class_name(filter_name)
    return "active" if filter_name == @filter
  end
end

app/views/events/_event.html.erb
  <div class="ev-header">
    <div class="ev-time">
      <%= event.datetime.strftime('%R') %>
    </div>
    <% if event.private %>
      <div class="ev-status">Privé</div>
    <% else %>
      <div class="ev-status">Public</div>
    <% end %>
  </div>

  <div class="ev-content">
    <div class="ev-photo">
      <% if event.user.photo? %>
        <%= cl_image_tag event.user.photo.path, class: 'ev-avatar', width: 200, height: 200, crop: :fill , data: {toggle: "tooltip"}, title: event.user.full_name %>
      <% else %>
        <%= image_tag 'avatar.jpg', class: 'ev-avatar', width: 200, height: 200, crop: :fill , data: {toggle: "tooltip"}, title: event.user.full_name %>
      <% end %>
    </div>

    <%= link_to event_path(event), class: 'ev-type' do %>
      <span class="events-type-underline" >
        <%= event.type_of %>
        <% if event.time_goal %>
          <%= event.time_goal_to_s %>
        <% else %>
          <%= event.trail_goal %> kms
        <% end %>
      </span>
    <% end %>

      <% if event.joined?(current_user) %>
      <div class="ev-validations">
      <% case event.participations.find_by(user: current_user).status %>
        <% when "going" %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "going"), method: :patch, style: "color: #00FF80 !important; font-size: 30px",remote: true do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "maybe"), method: :patch, remote: true do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "can t go"), method: :patch, remote: true do %>
            <i class="fa fa-times" data-toggle="tooltip" title="Je n'y vais pas"></i>
          <% end %>
        <% when "maybe" %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "going"), method: :patch,remote: true do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "maybe"), method: :patch, style: "color: #FF8000 !important; font-size: 30px", remote: true do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "can t go"), method: :patch, remote: true do %>
            <i class="fa fa-times" data-toggle="tooltip" title="Je n'y vais pas"></i>
          <% end %>
        <% when "can t go" %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "going"), method: :patch,remote: true do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "maybe"), method: :patch, remote: true do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
          <%= link_to participation_path(event.participations.find_by(user: current_user), status: "can t go"), method: :patch, style: "color: red !important; font-size: 30px", remote: true do %>
            <i class="fa fa-times" data-toggle="tooltip" title="Je n'y vais pas"></i>
          <% end %>
        <% end %>
        </div>
      <% else %>
        <div  class="ev-validations" id="create_participation">
          <%= link_to event_participations_path(event, status: "going"), method: :post, remote: true do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
          <%= link_to event_participations_path(event, status: "maybe"), method: :post, remote: true do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
        </div>
      <% end %>
  </div>

app/views/events/_events.html.erb
<h4 class="events-counter"> <%= pluralize events.size, "résultat" %></h4>
<% today = Date.today %>
<% events_sorted.each do |date, e| %>
  <div class="events-date-bg">
    <div class="events-date">
      <div>
        <i class="fa fa-calendar" aria-hidden="true"></i>
        <% if date == today %>
          Aujourd'hui
        <% elsif date == (today + 1.days) %>
          Demain
        <% else %>
          <%= date.strftime('%e %B %Y') %>
        <% end %>
      </div>
    </div>
    <div class="box">
    <% e.each do |event| %>
      <div class="ev" id="event_<%= event.id %>">
        <% if @filter == 'challenge' %>
          <%= render 'challenge', event: event %>
        <% else %>
          <%= render 'event', event: event %>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
<% end %>

app/views/events/_message.html.erb
<% class_name = (message.user == current_user) ? "reverse" : "" %>

<div class="message <%= class_name %>" id="message_<%= message.id %>">
  <%= render "users/avatar_xsmall", user: message.user %>

  <div class="message-box">
    <div class="message-header">
      <p>
        <strong> <%= message.user.first_name %> <%= message.user.last_name %></strong> -
        <%= time_ago_in_words(message.created_at) %> ago
      </p>
    </div>
    <div class="message-content">
      <p><%= message.content %></p>
    </div>
  </div>

</div>

app/views/events/_message_box.html.erb
<% if policy(@message).create? %>
  <%= simple_form_for([@event, @message], remote: true, :html=> { class: 'form-inline' }) do |f| %>
    <%= f.input :content, as: :string, label: false, placeholder: "votre message", input_html: {width: "400px"}  %>
    <%= f.button :submit, value: 'Postez', class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/events/_new.html.erb
  <%= simple_form_for([event], remote: true) do |f| %>
    <div class="form-group">
      <div class="row error-msg-form">
        <div class="col-xs-6">
          <a class="btn btn-default status status_on" id="public">Public</a>
        </div>
        <div class="col-xs-6">
          <a class="btn btn-default status" id="private">Privé</a>
        </div>
      </div>
    </div>
    <%= f.input :private, as: :hidden %>
    <%= f.input :type_of, autofocus: true, label: false, placeholder: "Type of event", collection: Event::MEETING, prompt: "Type d'événement*" %>
    <div class="form-group">
      <div class="row">
        <div class="col-xs-6">
          <div class="input-group date" id="datepicker">
            <%= text_field_tag "event[datetime]", f.object.datetime.try(:to_date), for: "disabledTextInput", class: "form-control", placeholder: "Date*" %>
            <div class="input-group-addon" id="disabledTextInput">
              <span class="glyphicon glyphicon-th"></span>
            </div>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="time-form">
            <%= select_time(f.object.datetime.try(:to_time), {}, { class: "form-control time-select" }) %>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= f.label 'Objectif' %>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <%= f.input :time_goal,label: false ,placeholder: "Minutes*", input_html: { min: '1' } %>
      </div>
      <div class="col-xs-12 col-md-6">
        <%= f.input :trail_goal,label: false ,placeholder: "Kms*", input_html: { min: '1' } %>
      </div>
    </div>
    <%= f.input :meeting_point, label: false , placeholder: 'Lieu de rendez-vous*' %>
    <%= f.input :address, label: false ,placeholder: 'Adresse*' %>
    <div class="text-center" id="private-suite">
      <div class="row">
        <div class="col-xs-6">
          <div class="">
            <a class="btn choice" id="colleagues">Ajouter vos collègues</a>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="">
            <%= link_to 'Random challenger',users_random_path ,class: "btn choice", id: "random", method: :post, remote: true %>
          </div>
        </div>
      </div>
      <div id="colleagues-choice">
        <%= f.association :users, collection: User.where.not(id: current_user.id), label: false, label_method: :full_name, value_method: :id, class: "form-control text-center" %>
      </div>
      <div id="random-choice"></div>
    </div>
    <br>
    <div class="text-center">
      <%= f.button :submit, class: "btn-primary", value: "Challenger" %>
    </div>
  <% end %>

  <% content_for :after_js do %>
    <script>
      $(document).ready(function() {
        setEventType();
        callDatePicker();
        setChosenSelect();
        setPrivateChoice();
      })
    </script>
  <% end %>

app/views/events/_participations.html.erb
  <% participation = @event.participations.find_by(user: current_user) %>

  <div class="participation_all">
    <div class="participation_header">
      <div><h4>Les Runners qui ont dit oui!</h4></div>
      <div class="participation_icone">
        <% if @event.joined?(current_user) %>
          <%= link_to participation_path(participation, status: "going", type: "show"), method: :patch, remote: true, class: (participation.status == "going" ? "going" : "" )  do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
        <% else %>
           <%= link_to event_participations_path(@event, status: "going", type: "show"), method: :post, remote: true do %>
            <i class="fa fa-check" data-toggle="tooltip" title="J'y vais!"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="particpation_avatar">
      <% @event.participations.each do |participation| %>
        <%if participation.status == "going" %>
          <div class="avatar_user">
            <%= render "users/avatar_small", user: participation.user %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr class="green-line">
  <div class="participation_all">
    <div class="participation_header">
      <div><h4>Les Runners qui hésitent encore!</h4></div>
      <div class="participation_icone">
        <% if @event.joined?(current_user) %>
          <%= link_to participation_path(participation, status: "maybe", type: "show"), method: :patch, remote: true, class: (participation.status == "maybe" ? "maybe" : "" ) do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
        <% else %>
          <%= link_to event_participations_path(@event, status: "maybe", type: "show"), method: :post, remote: true do %>
            <i class="fa fa-question" data-toggle="tooltip" title="Peut-être"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="particpation_avatar">
      <% @event.participations.each do |participation| %>
        <%if participation.status == "maybe" %>
          <div class="avatar_user">
            <%= render "users/avatar_small", user: participation.user %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr class="green-line">
  <div class="participation_all">
    <div class="participation_header">
      <div><h4>Les Runners qui ont dit non!</h4></div>
      <div class="participation_icone">
        <% if @event.joined?(current_user) %>
          <%= link_to participation_path(participation, status: "can t go", type: "show"), method: :patch, remote: true, class: (participation.status == "can t go" ? "dont_go" : "" ) do %>
            <i class="fa fa-times" data-toggle="tooltip" title="Je n'y vais pas"></i>
          <% end %>
        <% else %>
          <%= link_to event_participations_path(@event, status: "can t go", type: "show"), method: :post, remote: true do %>
            <i class="fa fa-times" data-toggle="tooltip" title="Je n'y vais pas"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="particpation_avatar">
      <% @event.participations.each do |participation| %>
        <%if participation.status == "can t go" %>
          <div class="avatar_user">
            <%= render "users/avatar_small", user: participation.user %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/events/_static_map.html.erb
<div class = "white-background">
  <h5 pad-bot>
    <i class="fa fa-map-marker color-icon" aria-hidden="true"></i>
    Adresse de l'activité : <%= @event.address %>
  </h5>
  <div class="banner-map" style='background-image: url("https://maps.googleapis.com/maps/api/staticmap?center=<%= @event.address %>&zoom=15&key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>&size=1200x600&sensor=false&maptype=roadmap&markers=color:red|<%= @event.address %>"); height: 300px; background-size: cover;background-position: center center'>
  </div>
</div>

<!-- <div id="map" style="width: 100%;" class="smooth-scrollable"></div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<script type="text/javascript">
var myLatlng = new google.maps.LatLng(48.852937,2.364178);

var myOptions = {
  zoom: 16,
  center: myLatlng,
  scrollwheel: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}]
};

var map = new google.maps.Map(document.getElementById('map'), myOptions);
var marker = new google.maps.Marker({
  position: myLatlng,
  map: map,
  title:"You are here!"
});
</script> -->

app/views/events/create.js.erb
// Here you will write *javascript* that would be executed by the browser
<% if @event.errors.any? %>
  // Render new review form with errors
  $('#new_event').html("<%= j render 'new', event: @event %>");
  setEventType();
  callDatePicker();
  setChosenSelect();
  setPrivateChoice();
<% else %>
  // Redirect to event page
  window.location = "<%= event_path(@event) %>";
<% end %>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="event-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'jogg.jpg' %>);">
  <h2 class="events-list-title text-center">Prochains événements</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 blue-nav allevents">
      <ul class="nav index-menu">
        <li class="all-child hvr-underline-from-left"><%= link_to 'Mes Run', events_path(filter: 'Own_run') %></li>
        <li class="all-child hvr-underline-from-left"><%= link_to 'Run publics', events_path(filter: 'public') %></li>
        <li class="all-child hvr-underline-from-left"><%= link_to 'Invitations', events_path(filter: 'private') %></li>
      </ul>
    </div>
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="events_content">
      <% if @filter == 'Own_run' %>
        <h4 class="mybuddies-title">Les run que j'organise</h4>
        <%= render 'events/events', events: @events, events_sorted: @events_sorted %>
        <h4 class="mybuddies-title">Les run auxquels je participe</h4>
        <%= render 'events/events', events: @my_participations, events_sorted: @my_participations_sorted %>
      <% else %>
        <%= render 'events/events', events: @events, events_sorted: @events_sorted %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% case @event.type_of %>
  <% when "Run fractionné" %>
    <% photo = "interval.jpg" %>
  <% when "Run endurance" %>
    <% photo = "endurance.jpg" %>
  <% when "Run rapide" %>
    <% photo = "cool_run.jpg" %>
  <% when "Blabla run" %>
    <% photo = "chatting_run.jpg" %>
  <% when "Marche rapide" %>
    <% photo = "runners-feet.jpg" %>
  <% else %>
    <% photo = "pleasant_walk.jpg" %>
  <% end %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= image_path photo, width: 600, height: 300, crop: :fill %>);"></div>

  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <div class="event">
          <div class="event_header">
            <div class='event-date'>
              <div class= "date-show">
                <div class="public_private">
                  <% if @event.private %>
                    <%= "PRIVE" %>
                  <% else %>
                    <%= "PUBLIC" %>
                  <% end  %>
                </div>
                <span style="margin-left: 20px;"> <%= @event.datetime.strftime('%e %B %Y') %> - <%= @event.datetime.strftime('%H:%M') %> </span>
              </div>
              <div class="event_type">
                <div class="detailed-type">
                  <h3>
                   <%= @event.type_of %> -
                     <% if @event.time_goal %>
                       <%= @event.time_goal_to_s %>
                     <% end %>
                     <% if @event.trail_goal %>
                        <%= @event.trail_goal %> km
                     <% end %>
                  </h3>
                  <p>
                    <% if policy(@event).edit? %>
                      <%= link_to edit_event_path(@event) do %>
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                      <% end %>
                    <% end %>
                    <% if policy(@event).destroy? %>
                      <%= link_to event_path, method: :delete do %>
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      <% end %>
                    <% end %>
                  </p>
                </div>
                <div class="event_update_delete">
                  <i class="fa fa-map-marker"></i> RDV - <%= @event.meeting_point %>
                </div>
              </div>
            </div>
            <div class="organizer-avatar">
              <%= render "users/avatar", user: @event.user %>
              <div class="organizer">
                <p>Organisé par <%= @event.user.first_name.capitalize %> <%= @event.user.last_name.capitalize  %></p>
              </div>
            </div>
          </div>
          <div class="event-details">
            <div class="description">
              <div class="description-container">
                <div class="description-activity">
                  <% unless @event.description.blank? %>
                    <h4>
                      <i class="fa fa-pencil-square-o color-icon" aria-hidden="true"></i>
                      <%= "Description de l'activité" %>
                    </h4>
                    <p><%= @event.description %></p>
                  <% end %>
                </div>
                <div class="messages">
                  <h4>
                    <i class="fa fa-comments color-icon" aria-hidden="true"></i>
                    <%= "Messages" %>
                  </h4>
                  <% unless @event.messages.empty? %>
                    <% @event.messages.each do |message| %>
                        <%= render 'events/message', message: message %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="description-footer">
                <%= render 'events/message_box' %>
              </div>
            </div>
            <div class="participation">
              <%= render "events/participations", event: @event %>
            </div>
          </div>
          <div class="photos">
            <div class="photos_header">
              <h4><%= "Vos selfies!" %></h4>
              <div class="photos_btn">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addPhotos">
                  <i class="fa fa-camera-retro" aria-hidden="true"></i>
                   Postez vos selfies!
                </button>
              </div>
            </div>
            <div class="container">
              <div class="row">
                <% unless @event.photos.nil? %>
                  <% @event.photos.each do |photo| %>
                    <div class="col-xs-4 col-sm-3 col-sm-2">
                      <div class="photo pad-top">
                        <%= cl_image_tag photo.path, width: 250, height: 250, crop: :fill %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
                </div>
              </div>
          </div>
          <div class="back_events">
            <i class="fa fa-arrow-left color-icon" aria-hidden="true"></i>
            <%= link_to "Revenir aux événements", events_path %>
          </div>
        <% if @event.latitude &&  @event.longitude %>
          <%= render "events/static_map", event: @event %>
        <% end %>
      </div>
    </div>
  </div>
</div>

 <div class="modal fade" id="addPhotos" tabindex="-1" role="dialog" aria-labelledby="addPhotosLabel">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <h4 class="modal-title" id="addPhotosLabel">Partagez vos selfies! </h4>
       </div>
       <div class="modal-body">
        <%= simple_form_for(@event, :url => add_pictures_path, :method => :patch) do |f| %>
        <%= f.input :photos, as: :attachinary  %>
        <%= f.button :submit, value: 'Postez', class: "btn btn-primary" %>
        <% end %>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       </div>
     </div>
   </div>
 </div>