config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  patch "events/:id/add_pictures" => "events#add_pictures", as: "add_pictures"

  resources :events do
    resources :participations, only: [:create]
    resources :messages, only: [:create]
  end
  get '/profile' => 'users#profile'
  post '/users/random' => 'users#random'
  resources :users, only: [ :edit, :update, :destroy ]
  resources :participations, only: [:update, :destroy]
  resources :activities, only: [:index]
  mount Attachinary::Engine => "/attachinary"
  get 'activities/:id/done' => "activities#mark_as_read", as: :read_activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_after_action :verify_policy_scoped
  skip_after_action :verify_authorized

  def index
    event_ids = current_user.events_as_participant.map do |event|
      event.id
    end
    @activities = PublicActivity::Activity.order("created_at desc").where(trackable_id: event_ids)
    @activities.where(read_at: nil).each do |activity|
      activity.read_at = DateTime.now
      activity.save
    end
  end

  def mark_as_read
    activity = PublicActivity::Activity.find(params[:id])
    activity.read_at = DateTime.now
    activity.save
    respond_to do |format|
      format.js
      format.html {redirect_to root_path}
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_index.html.erb
<% activities.each do |activity| %>
  <div class="notification">
    <%= activity.owner.first_name.capitalize %> <%= activity.owner.last_name.capitalize %>
    <%= render_activity activity %>
    <%= link_to read_activity_path(activity), class: "pull-right", remote: true do %>
      <i class="fa fa-check"></i>
    <% end %>
  </div>
<% end %>

app/views/activities/index.html.erb
<h3>
  Notifications
</h3>
<% @activities.each do |activity| %>
    <div class="#activity">
      <h5>
        <strong>
          <%= activity.owner.first_name.capitalize %> <%= activity.owner.last_name.capitalize %>
        </strong>
        <%= render_activity activity %>
      </h5>
    </div>
  </div>
<% end %>

app/views/activities/mark_as_read.js.erb
$('#notifications').html('<%= j render "shared/notifications", activities: @activities %>');